name: Bug
description: Bug report
title: "[Bug] <title>"
labels: ["type:bug"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Description
      placeholder: "What happened and what did you expect?"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: "1) ... 2) ... 3) ..."
  - type: input
    id: expected
    attributes:
      label: Expected behaviour