name: Documentation
description: Docs task
title: "[Docs] <title>"
labels: ["phase:planning"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
  - type: textarea
    id: artefacts
    attributes:
      label: Artefacts to produce
      placeholder: "requirements.md, architecture.md, tasks.md, test-plan.md"