name: Sync Claude Sub-Agents
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 1 * * *"  # nightly at 01:00 UTC
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Sync agents
        run: bash scripts/agents/sync.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(agents): sync upstream Claude sub-agents"
          title: "chore: sync upstream Claude sub-agents"
          body: "Synced from upstream via scripts/agents/sync.sh"
          branch: "chore/agents-sync"
          add-paths: |
            .claude/**